title: "ISTOK HOME – Проектирование и дизайн интерьеров"
author: "istokhome.kz"
description: "Архитектeура | Дизайн интерьера | BIM"
theme: minima

# ссылки в футере
social_links:

  instagram: instagram.com/atm.arch

# язык сайта
lang: ru
