title: "ISTOK HOME"
author: "ISTOK HOME"
description: "Архитектура и дизайн интерьеров"
theme: minima
skin: dark   # включаем тёмную тему

header_pages:
  - index.md
  - projects.md
  - services.md
  - about.md

# ссылки в футере
social_links:
  instagram: https://www.instagram.com/atm.arch/

# язык сайта
lang: ru
